#!/usr/bin/env sh
# shellcheck disable=SC1090
#
# Copyright (c) 2023 Justin Teague
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

Prgnam='mailg'
Version='0.0.42'
Verbose=0
Debug=0
Config_Defaults="
$PWD/$Prgnam.conf
$PWD/.$Prgnam.conf
$HOME/.$Prgnam.conf
${XDG_CONFIG_HOME:-$HOME/.config}/$Prgnam.conf
"
# Envioronment variables
MAILGUN_API_KEY="${MAILGUN_API_KEY:-}" 
MAILGUN_API_DOMAIN="${MAILGUN_API_DOMAIN:-}"
MAILGUN_API_URL="${MAILGUN_API_URL:-https://api.mailgun.net/v3}"
MAILGUN_FROM_ADDRESS="${MAILGUN_FROM_ADDRESS:-}"  # Optional
MAILGUN_FROM_NAME="${MAILGUN_FROM_NAME:-}"        # Optional

# Usage
usage() {
  cat << EOF
$Prgnam -- $Version
Send mail via mailgun and curl from the command-line.

Usage: $Prgnam [-vdE] [-s subject] [-r from email] [-F from name] to-address

    -v    Verbose mode.
    -d    Debug mode.
    
    -C    Configuration file.
    -s    Subject.
    -r    From email.
    -F    From name.

ENVIRONMENT VARIABLES

    MAILGUN_API_KEY
    MAILGUN_API_DOMAIN
    MAILGUN_API_URL (default: https://api.mailgun.net/v3)
    MAILGUN_FROM_ADDRESS
    MAILGUN_FROM_NAME
EOF
}

# STDIN/STDOUT Functions
out() {
  printf %s\\n "$*"
}

err() {
  >&2 printf %s\\n "$*"
}

die() {
  err "$*"
  exit 1
}

info() {
  if [ "$Verbose" -ge 1 ]; then
    err "$*"
  fi
}

debug() {
  if [ "$Debug" -ge 1 ]; then
    err "DEBUG: $*"
  fi
}

main() {
  subj=""
  from_addr=""
  from_name=""
  message=""
  attach=""
  from=""

  # Get message from stdin
  if [ -p /dev/stdin ] || [ -f /dev/stdin ]; then
    message="$(cat)"
    debug "message=$message"
  fi

  # Check for configuration file
  for _conf in $Config_Defaults; do
    if [ -r "$_conf" ]; then
      . "$_conf" || exit 1
    fi
  done

  while getopts ':vdC:a:F:r:s:' OPTION; do
    case "$OPTION" in
      d) Debug=1 ;;
      v) Verbose=1 ;;
      a) attach="$OPTARG" ;;
      C) . "$OPTARG" || exit 1 ;;
      F) from_name="$OPTARG" ;;
      r) from_addr="$OPTARG" ;;
      s) subj="$OPTARG" ;;
      *) usage ; exit 1 ;;
    esac
  done
  shift "$((OPTIND -1))"

  debug "Verbose=$Verbose"
  debug "Debug=$Debug"
  debug "attach=$attach"
  debug "subj=$subj"
  debug "from_addr=$from_addr"
  debug "from_name=$from_name"
  debug "recipients=$*"
  
  # Check for To: address
  if [ -z "$1" ]; then
    die "No recipient address."
  fi

  # Build recipient array
  count=0
  for _to in "$@"; do
    [ "$count" -eq 0 ] && set --; count=$((count +1))
    set -- "$@" -F "text=$_to"
  done

  # Check from Environment variables
  if [ -z "$MAILGUN_API_KEY" ]; then
    die "MAILGUN_API_KEY unset."
  fi
  if [ -z "$MAILGUN_API_DOMAIN" ]; then
    die "MAILGUN_API_DOMAIN unset."
  fi
  if [ -z "$MAILGUN_API_URL" ]; then
    die "MAILGUN_API_URL unset."
  fi
  
  # Build "From" address
  if [ -z "${from_addr:=$MAILGUN_FROM_ADDRESS}" ]; then
    from_addr="${USER:-nobody}@$MAILGUN_API_DOMAIN"
  fi

  if [ -n "${from_name:=$MAILGUN_FROM_NAME}" ]; then
    from="$from_name <$from_addr>"
  else
    from="$from_addr"
  fi
  debug "from=$from"
  return

  # Post message
  _res=$(mktemp 2>&1) || die "$_res"
  if ! _ret=$(curl -sS \
    -w "%{http_code}\n" \
    -o "$_res" \
    --user "api:$MAILGUN_API_KEY" \
    "$MAILGUN_API_URL/$MAILGUN_API_DOMAIN/messages" \
    -F "subject=$subject" \
    -F "text=$message" \
    -F "from=$from" \
    "$@" 2>&1); then
    err "curl error: $_res"
    return 1
  fi

  info "$(cat _res)"
  rm "$_res"  # cleanup temp file

  if [ "$_ret" -ne 200 ]; then
    err "HTTP error code: $_ret"
    return 1
  fi
}

main "$@"
